# Generated by Django 3.2.5 on 2024-05-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorisation', '0003_auto_20240503_1841'),
        ('clubs', '0007_auto_20240505_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=150)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='clubs.clubmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserMeetingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorisation.user')),
            ],
        ),
    ]
