# Generated by Django 3.2.5 on 2024-06-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
