# Generated by Django 3.2.5 on 2024-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
