# Generated by Django 3.2.5 on 2024-05-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_auto_20240503_1841'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authorisation.user'),
        ),
        migrations.CreateModel(
            name='UserClubModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorisation.user')),
            ],
        ),
    ]
