# Generated by Django 3.2.5 on 2024-05-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_auto_20240503_1841'),
        ('clubs', '0002_auto_20240503_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorisation.user'),
        ),
    ]
