# Generated by Django 3.2.5 on 2024-05-04 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_clubmodel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmodel',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='clubs.clubmodel'),
        ),
    ]
