# Generated by Django 3.2.5 on 2024-05-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_meetingmodel_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclubmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
