# Generated by Django 3.2.5 on 2024-05-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_auto_20240503_1841'),
        ('clubs', '0005_alter_userclubmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeetingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.meetingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorisation.user')),
            ],
        ),
    ]
