# Generated by Django 3.2.5 on 2024-05-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_usermeetingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeetingmodel',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='usermeetingmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='MeetingModel',
        ),
        migrations.DeleteModel(
            name='UserMeetingModel',
        ),
    ]
