# Generated by Django 3.2.5 on 2024-05-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20240505_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
