# Generated by Django 3.2.5 on 2024-06-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_clubmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
