# Generated by Django 3.2.5 on 2024-06-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorisation', '0001_initial'),
        ('genres', '0001_initial'),
        ('clubs', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(db_column='city_fias', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='clubs.citymodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='users', to='genres.GenresModel'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='permissions', to='auth.Permission'),
        ),
    ]
