# Generated by Django 3.2.5 on 2024-05-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('authorisation', '0002_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clubs',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(db_column='city_fias', on_delete=django.db.models.deletion.PROTECT, to='clubs.citymodel'),
        ),
    ]
