# Generated by Django 3.2.5 on 2024-05-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0004_auto_20240508_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
