# Generated by Django 3.2.5 on 2024-05-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('authorisation', '0007_auto_20240508_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='users', to='genres.GenresModel'),
        ),
    ]
