# Generated by Django 3.2.5 on 2024-05-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20240505_0508'),
        ('authorisation', '0010_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(db_column='city_fias', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='clubs.citymodel'),
        ),
    ]
