# Generated by Django 3.2.5 on 2024-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
